/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package etapa03guia01ejercicio04;

import javax.swing.table.DefaultTableModel;

/**
 *
 * @author kalema
 */
public class BusquedaPorNombre extends javax.swing.JInternalFrame {
public DefaultTableModel modelo=new DefaultTableModel(){
    @Override
    public boolean isCellEditable(int fila,int columna){
        return false;
    }
};

    /**
     * Creates new form BusquedaPorNombre
     */
    public BusquedaPorNombre() {
        initComponents();
        armarColumna();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jtBusqueda = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtResultado = new javax.swing.JTable();

        jLabel1.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("LISTADO POR DESCRIPCIÓN");

        jLabel2.setText("Ingrese su búsqueda");

        jtBusqueda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtBusquedaActionPerformed(evt);
            }
        });
        jtBusqueda.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtBusquedaKeyReleased(evt);
            }
        });

        jtResultado.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jtResultado);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(99, 99, 99)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jtBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 323, Short.MAX_VALUE))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jtBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 58, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtBusquedaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtBusquedaKeyReleased
        // TODO add your handling code here:
         borrarFila();
         
        for (Productos elProducto : Menu.listado) {
            //System.out.println("veo por consola "+jtBusqueda.getText());
            if(jtBusqueda.getText().isEmpty()){
                borrarFila();
            }else if(elProducto.getDescripcion().startsWith(jtBusqueda.getText())){
                modelo.addRow(new Object[]{
                elProducto.getCodigo(),elProducto.getMarca(),elProducto.getRubro(),
                elProducto.getPrecio(),elProducto.getStock(),elProducto.getDescripcion()
            });
            }
            
        }
         
    }//GEN-LAST:event_jtBusquedaKeyReleased

    private void jtBusquedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtBusquedaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtBusquedaActionPerformed

             
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jtBusqueda;
    private javax.swing.JTable jtResultado;
    // End of variables declaration//GEN-END:variables

private void armarColumna(){
    modelo.addColumn("Código");
    modelo.addColumn("Marca");
    modelo.addColumn("Categoria");
    modelo.addColumn("Precio");
    modelo.addColumn("Stock");
    modelo.addColumn("Descripción");
    jtResultado.setModel(modelo);
}

            

private void borrarFila(){
    int fila=jtResultado.getRowCount()-1;
    for(int f=fila;f>=0;f--){
        modelo.removeRow(f);
    }
//    for (int i = fila; i >=0; i--) {
//      
//        if(i==1){
//            f=(Integer)modelo.getValueAt(i, 0);
//            System.out.println(f);
//            modelo.removeRow(3);
//        }
//    }
}

}
